# ztn configuration file
pki:
  ca: /etc/ztn/ca.crt
  cert: /etc/ztn/host.crt
  key: /etc/ztn/host.key

static_host_map:
  "172.31.252.1": ["68.183.59.195:5415"]
  "172.31.252.2": ["143.198.61.109:5415"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "172.31.252.1"
    - "172.31.252.2"

listen:
  host: 0.0.0.0
  port: 5415
  read_buffer: 10485760
  write_buffer: 10485760

tun:
  dev: ztn0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      groups:
        - mgmt

    - port: 22
      proto: tcp
      groups:
        - ssh

